[package]
edition = "2018"
name = "napi-uuid"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = {version = "2.0.0-beta.4"}
napi-derive = {version = "2.0.0-beta.3"}
uuid = {version = "0.8", features = ["v4"]}

[build-dependencies]
napi-build = "1"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
